import React from "react";
import LegalCard from "./LegalCard";

const TopLegalExperts = () => {
  const lawyers = [
    {
      _id: "lawyer-001",
      name: "Barrister Sarah Ahmed",
      email: "sarah.ahmed@legalease.com",
      image: "https://i.pravatar.cc/300?img=1",
      specialization: "Corporate Law",
      bio: "Experienced corporate lawyer specializing in mergers, acquisitions, and business compliance.",
      fee: 120,
      status: "available",
      location: "Dhaka, Bangladesh",
      experience: 12,
      totalHires: 185,
      createdAt: "2025-03-15",
    },
    {
      _id: "lawyer-002",
      name: "Advocate Tanvir Hasan",
      email: "tanvir.hasan@legalease.com",
      image: "https://i.pravatar.cc/300?img=2",
      specialization: "Criminal Law",
      bio: "Dedicated criminal defense attorney with extensive courtroom experience.",
      fee: 90,
      status: "available",
      location: "Chattogram, Bangladesh",
      experience: 8,
      totalHires: 132,
      createdAt: "2025-04-10",
    },
    {
      _id: "lawyer-003",
      name: "Barrister Nusrat Jahan",
      email: "nusrat.jahan@legalease.com",
      image: "https://i.pravatar.cc/300?img=3",
      specialization: "Family Law",
      bio: "Helping families navigate divorce, child custody, and inheritance matters.",
      fee: 75,
      status: "busy",
      location: "Dhaka, Bangladesh",
      experience: 7,
      totalHires: 149,
      createdAt: "2025-02-20",
    },
    {
      _id: "lawyer-004",
      name: "Advocate Mahmudul Karim",
      email: "mahmud.karim@legalease.com",
      image: "https://i.pravatar.cc/300?img=4",
      specialization: "Property Law",
      bio: "Expert in land disputes, property registration, and real estate transactions.",
      fee: 85,
      status: "available",
      location: "Rajshahi, Bangladesh",
      experience: 10,
      totalHires: 101,
      createdAt: "2025-05-01",
    },
    {
      _id: "lawyer-005",
      name: "Barrister Fahim Rahman",
      email: "fahim.rahman@legalease.com",
      image: "https://i.pravatar.cc/300?img=5",
      specialization: "Tax Law",
      bio: "Specialist in corporate taxation, VAT compliance, and tax dispute resolution.",
      fee: 130,
      status: "available",
      location: "Dhaka, Bangladesh",
      experience: 14,
      totalHires: 220,
      createdAt: "2025-01-12",
    },
    {
      _id: "lawyer-006",
      name: "Advocate Rifat Chowdhury",
      email: "rifat.chowdhury@legalease.com",
      image: "https://i.pravatar.cc/300?img=6",
      specialization: "Cyber Law",
      bio: "Advises clients on cybercrime, digital security, and technology regulations.",
      fee: 110,
      status: "busy",
      location: "Sylhet, Bangladesh",
      experience: 6,
      totalHires: 88,
      createdAt: "2025-06-01",
    },
    {
      _id: "lawyer-007",
      name: "Barrister Ayesha Sultana",
      email: "ayesha.sultana@legalease.com",
      image: "https://i.pravatar.cc/300?img=7",
      specialization: "Immigration Law",
      bio: "Provides legal support for visas, immigration appeals, and residency matters.",
      fee: 95,
      status: "available",
      location: "Khulna, Bangladesh",
      experience: 9,
      totalHires: 113,
      createdAt: "2025-03-28",
    },
    {
      _id: "lawyer-008",
      name: "Advocate Imran Hossain",
      email: "imran.hossain@legalease.com",
      image: "https://i.pravatar.cc/300?img=8",
      specialization: "Civil Law",
      bio: "Handles civil litigation, contract disputes, and consumer rights cases.",
      fee: 70,
      status: "available",
      location: "Barishal, Bangladesh",
      experience: 5,
      totalHires: 76,
      createdAt: "2025-04-18",
    },
    {
      _id: "lawyer-009",
      name: "Barrister Shakib Mahmud",
      email: "shakib.mahmud@legalease.com",
      image: "https://i.pravatar.cc/300?img=9",
      specialization: "Corporate Law",
      bio: "Works with startups and enterprises on legal structuring and compliance.",
      fee: 125,
      status: "busy",
      location: "Dhaka, Bangladesh",
      experience: 11,
      totalHires: 174,
      createdAt: "2025-02-08",
    },
    {
      _id: "lawyer-010",
      name: "Advocate Mst. Farzana Akter",
      email: "farzana.akter@legalease.com",
      image: "https://i.pravatar.cc/300?img=10",
      specialization: "Family Law",
      bio: "Experienced family lawyer focused on mediation and family dispute resolution.",
      fee: 80,
      status: "available",
      location: "Cumilla, Bangladesh",
      experience: 7,
      totalHires: 97,
      createdAt: "2025-05-20",
    },
    {
      _id: "lawyer-011",
      name: "Barrister Abdullah Al Mamun",
      email: "abdullah.mamun@legalease.com",
      image: "https://i.pravatar.cc/300?img=11",
      specialization: "Criminal Law",
      bio: "Known for effective criminal defense strategies and legal advocacy.",
      fee: 100,
      status: "available",
      location: "Mymensingh, Bangladesh",
      experience: 13,
      totalHires: 143,
      createdAt: "2025-01-25",
    },
    {
      _id: "lawyer-012",
      name: "Advocate Jannatul Ferdous",
      email: "jannatul.ferdous@legalease.com",
      image: "https://i.pravatar.cc/300?img=12",
      specialization: "Property Law",
      bio: "Provides legal guidance on land ownership, transfer, and property disputes.",
      fee: 85,
      status: "busy",
      location: "Rangpur, Bangladesh",
      experience: 8,
      totalHires: 109,
      createdAt: "2025-06-05",
    },
  ];
  return (
    <div>
      <div>
        <LegalCard lawyers={lawyers}></LegalCard>
      </div>
    </div>
  );
};

export default TopLegalExperts;
